apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  # Cluster id should be something like cluster-name-2p2t4 (last digit are random numbers generated during creation)
  name: REPLACE-CLUSTER-ID-infra-westeurope1
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: REPLACE-CLUSTER-ID
    machine.openshift.io/cluster-api-machine-role: worker
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: REPLACE-CLUSTER-ID
      machine.openshift.io/cluster-api-machineset: REPLACE-CLUSTER-ID-infra-westeurope1
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: REPLACE-CLUSTER-ID
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: REPLACE-CLUSTER-ID-infra-westeurope1
    spec:
      taints:
      - effect: NoSchedule
        key: node.ocs.openshift.io/storage
        value: "true"
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
          cluster.ocs.openshift.io/openshift-storage: ""
      providerSpec:
        value:
          osDisk:
            diskSizeGB: 1024
            managedDisk:
              storageAccountType: Premium_LRS
            osType: Linux
          networkResourceGroup: aro4-shared-weu
          publicLoadBalancer: REPLACE-CLUSTER-ID
          userDataSecret:
            name: worker-user-data
          vnet: aro-vnet-weu
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          zone: '1'
          metadata:
            creationTimestamp: null
          publicIP: false
          resourceGroup: aro4-infra-weu
          kind: AzureMachineProviderSpec
          location: westeurope
          vmSize: Standard_D4s_v3
          image:
            offer: aro4
            publisher: azureopenshift
            resourceID: ''
            sku: aro_46
            version: 46.82.20201126
          subnet: aro4-weu-workers
          apiVersion: azureproviderconfig.openshift.io/v1beta1